// Add a review
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";


// get all review --> admin

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


// delete review admin =>
export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

// Edit review
export const EDIT_REVIEW_REQUEST = "EDIT_REVIEW_REQUEST";
export const EDIT_REVIEW_SUCCESS = "EDIT_REVIEW_SUCCESS";
export const EDIT_REVIEW_FAIL = "EDIT_REVIEW_FAIL";
export const EDIT_REVIEW_RESET = "EDIT_REVIEW_RESET";

// Like/Dislike review
export const LIKE_REVIEW_REQUEST = "LIKE_REVIEW_REQUEST";
export const LIKE_REVIEW_SUCCESS = "LIKE_REVIEW_SUCCESS";
export const LIKE_REVIEW_FAIL = "LIKE_REVIEW_FAIL";